# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pinecone < Formula
  desc "Pinecone CLI"
  homepage "https://www.pinecone.io"
  version "0.0.34"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/pinecone-io/cli/releases/download/v0.0.34/pinecone_Darwin_all.tar.gz"
    sha256 "95d355f9a39ffd98cab6f13e0a95a01dee24efca9daa3f22906be47dace37502"

    def install
      bin.install "pinecone"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pinecone-io/cli/releases/download/v0.0.34/pinecone_Linux_x86_64.tar.gz"
        sha256 "befc05ec67d3d715c51e6d96e0788dc911eeecc9ab79bd1ef8bae7ff04a6253a"

        def install
          bin.install "pinecone"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pinecone-io/cli/releases/download/v0.0.34/pinecone_Linux_arm64.tar.gz"
        sha256 "fef242aeee768a78c257dafd8ff6719442500c5c5c4037e20ee91b6473a803d0"

        def install
          bin.install "pinecone"
        end
      end
    end
  end

  test do
    system "#{bin} --help"
  end
end
