# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PineconeDev < Formula
  desc ""
  homepage ""
  version "0.0.16"
  license "Apache-2.0"
  depends_on :macos

  url "https://github.com/pinecone-io/cli/releases/download/v0.0.16/pinecone_Darwin_all.tar.gz"
  sha256 "6f09681b76d6f1c63e021c990467e3be435b0867dbcd9ca243784cd70a26b8e8"

  def install
    bin.install "pinecone"
  end

  test do
    system "#{bin} --version"
  end
end
