# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PineconeDev < Formula
  desc ""
  homepage ""
  version "0.0.19"
  license "Apache-2.0"
  depends_on :macos

  url "https://github.com/pinecone-io/cli/releases/download/v0.0.19/pinecone_Darwin_all.tar.gz"
  sha256 "6e17276c4116c2561c0f03846c7ede325ca09fdbc2b60c04e636bdeb79605e69"

  def install
    bin.install "pinecone"
  end

  test do
    system "#{bin} --version"
  end
end
