# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pinecone < Formula
  desc "Pinecone CLI"
  homepage "https://www.pinecone.io"
  version "0.0.59"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/pinecone-io/cli/releases/download/v0.0.59/pc_Darwin_all.tar.gz"
    sha256 "a1fb4046b9b17cf320503a12ff9faab78337c51dd5f78c69a1bdbfffeef720c9"

    def install
      bin.install "pc"
      bin.install_symlink "pc" => "pinecone"

      # Install man pages
      man1.install Dir["man/man1/*.1"]

      # Add aliases: pc*.1 -> pinecone*.1, etc
      Dir["man/man1/*.1"].each do |src|
        dest = File.basename(src).sub(/\Apc\b/, "pinecone") # Replace leading "pc" with "pinecone"
        man1.install src => dest
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinecone-io/cli/releases/download/v0.0.59/pc_Linux_x86_64.tar.gz"
      sha256 "6a1120c413c6799d7c25a4ee252eaffe266125223db5548cb838f5dee561f238"
      def install
        bin.install "pc"
        bin.install_symlink "pc" => "pinecone"

        # Install man pages
        man1.install Dir["man/man1/*.1"]

        # Add aliases: pc*.1 -> pinecone*.1, etc
        Dir["man/man1/*.1"].each do |src|
          dest = File.basename(src).sub(/\Apc\b/, "pinecone") # Replace leading "pc" with "pinecone"
          man1.install src => dest
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinecone-io/cli/releases/download/v0.0.59/pc_Linux_arm64.tar.gz"
      sha256 "54d5b2a2b9fee87885252116c1aa9871fb37540ded1e81463ad39d6ce1b2f697"
      def install
        bin.install "pc"
        bin.install_symlink "pc" => "pinecone"

        # Install man pages
        man1.install Dir["man/man1/*.1"]

        # Add aliases: pc*.1 -> pinecone*.1, etc
        Dir["man/man1/*.1"].each do |src|
          dest = File.basename(src).sub(/\Apc\b/, "pinecone") # Replace leading "pc" with "pinecone"
          man1.install src => dest
        end
      end
    end
  end

  test do
    system "#{bin}/pc --help"
  end
end
