name: Update pinecone-dev cli formula

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'CLI version'
        required: true
        default: '0.0.21'

jobs:
    publish:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Download checksums from latest release
          run: |
            curl "https://storage.googleapis.com/pinecone-cli/${{ inputs.version }}/pinecone_${{ inputs.version }}_checksums.txt" > /tmp/checksums.txt
            cat /tmp/checksums.txt

            mac_sha=$(cat /tmp/checksums.txt | grep pinecone_Darwin_all.tar.gz | awk '{print $1}')
            linux_intel_sha=$(cat /tmp/checksums.txt | grep pinecone_Linux_x86_64.tar.gz | awk '{print $1}')
            linux_arm_sha=$(cat /tmp/checksums.txt | grep pinecone_Linux_arm64.tar.gz | awk '{print $1}')

            echo 's/##RELEASE_VERSION##/${{ inputs.version }}/g' > sed_commands.sed
            echo "s/##MAC_SHA##/${mac_sha}/g" >> sed_commands.sed
            echo "s/##LINUX_INTEL_SHA##/${linux_intel_sha}/g" >> sed_commands.sed
            echo "s/##LINUX_ARM_SHA##/${linux_arm_sha}/g" >> sed_commands.sed

            sed -i -f sed_commands.sed .github/workflows/pinecone-dev.template.rb
            cat .github/workflows/pinecone-dev.template.rb > Formula/pinecone-dev.rb

        - name: Commit changes
          run: |
            git config --global user.email "clients@pinecone.io"
            git config --global user.name "Pinecone CI"
            git add Formula/pinecone-dev.rb
            git commit -m "Update pinecone-dev to version ${{ inputs.version }}"
            git push
